let rankList = [
    {
        rank: 1,
        name: "Rocky",
        year: 1999,
        score: 525,
        percentage: 100,
    },
    {
        rank: 2,
        name: "John",
        year: 1992,
        score: 500,
        percentage: 91,
    },
    {
        rank: 3,
        name: "Sang",
        year: 2003,
        score: 600,
        percentage: 99,
    },
    {
        rank: 4,
        name: "Andrew",
        year: 1995,
        score: 400,
        percentage: 89,
    },
    {
        rank: 5,
        name: "Jack",
        year: 1996,
        score: 500,
        percentage: 90,
    },
    {
        rank: 6,
        name: "Anna",
        year: 2002,
        score: 325,
        percentage: 95,
    },
    {
        rank: 7,
        name: "Oliver",
        year: 1997,
        score: 220,
        percentage: 89,
    },
    {
        rank: 8,
        name: "Harry",
        year: 1996,
        score: 680,
        percentage: 88,
    },
    {
        rank: 9,
        name: "Jacob",
        year: 1992,
        score: 480,
        percentage: 86,
    },
    {
        rank: 10,
        name: "Charlie",
        year: 2001,
        score: 560,
        percentage: 93,
    },
    {
        rank: 11,
        name: "Thomas",
        year: 1995,
        score: 345,
        percentage: 96,
    },
    {
        rank: 12,
        name: "George",
        year: 1994,
        score: 569,
        percentage: 89,
    },
    {
        rank: 13,
        name: "Oscar",
        year: 1991,
        score: 499,
        percentage: 85,
    },
    {
        rank: 14,
        name: "James",
        year: 1987,
        score: 521,
        percentage: 82,
    },
    {
        rank: 15,
        name: "William",
        year: 1992,
        score: 528,
        percentage: 95,
    },
    {
        rank: 16,
        name: "Daniel",
        year: 1998,
        score: 450,
        percentage: 88,
    },
    {
        rank: 17,
        name: "Emily",
        year: 2000,
        score: 610,
        percentage: 96,
    },
    {
        rank: 18,
        name: "Sophia",
        year: 1993,
        score: 520,
        percentage: 92,
    },
    {
        rank: 19,
        name: "Emma",
        year: 1999,
        score: 480,
        percentage: 89,
    },
    {
        rank: 20,
        name: "Michael",
        year: 1997,
        score: 390,
        percentage: 87,
    },
    {
        rank: 21,
        name: "Liam",
        year: 2004,
        score: 550,
        percentage: 94,
    },
    {
        rank: 22,
        name: "Benjamin",
        year: 1994,
        score: 410,
        percentage: 85,
    },
    {
        rank: 23,
        name: "Ethan",
        year: 1996,
        score: 480,
        percentage: 91,
    },
    {
        rank: 24,
        name: "Alexander",
        year: 1992,
        score: 550,
        percentage: 90,
    },
    {
        rank: 25,
        name: "Sebastian",
        year: 2001,
        score: 320,
        percentage: 94,
    },
    {
        rank: 26,
        name: "David",
        year: 1995,
        score: 240,
        percentage: 88,
    },
    {
        rank: 27,
        name: "Mia",
        year: 1998,
        score: 670,
        percentage: 95,
    },
    {
        rank: 28,
        name: "Ava",
        year: 1997,
        score: 470,
        percentage: 91,
    },
    {
        rank: 29,
        name: "Elijah",
        year: 2002,
        score: 580,
        percentage: 99,
    },
    {
        rank: 30,
        name: "Lucas",
        year: 1993,
        score: 380,
        percentage: 87,
    },
    {
        rank: 31,
        name: "Matthew",
        year: 1991,
        score: 520,
        percentage: 84,
    },
    {
        rank: 32,
        name: "Harper",
        year: 1994,
        score: 490,
        percentage: 92,
    },
    {
        rank: 33,
        name: "Daniel",
        year: 1996,
        score: 310,
        percentage: 86,
    },
    {
        rank: 34,
        name: "Charlotte",
        year: 1999,
        score: 590,
        percentage: 94,
    },
    {
        rank: 35,
        name: "Evelyn",
        year: 2000,
        score: 400,
        percentage: 89,
    },
    {
        rank: 36,
        name: "Lucy",
        year: 1995,
        score: 250,
        percentage: 88,
    },
    {
        rank: 37,
        name: "William",
        year: 1992,
        score: 460,
        percentage: 82,
    },
    {
        rank: 38,
        name: "Alexander",
        year: 1998,
        score: 640,
        percentage: 98,
    },
    {
        rank: 39,
        name: "Olivia",
        year: 1997,
        score: 550,
        percentage: 91,
    },
    {
        rank: 40,
        name: "Sophia",
        year: 2004,
        score: 380,
        percentage: 85,
    },
    {
        rank: 41,
        name: "James",
        year: 1996,
        score: 450,
        percentage: 93,
    },
    {
        rank: 42,
        name: "Benjamin",
        year: 1992,
        score: 390,
        percentage: 82,
    },
    {
        rank: 43,
        name: "Ethan",
        year: 1995,
        score: 530,
        percentage: 88,
    },
    {
        rank: 44,
        name: "Abigail",
        year: 1998,
        score: 380,
        percentage: 95,
    },
    {
        rank: 45,
        name: "Charlotte",
        year: 1997,
        score: 510,
        percentage: 91,
    },
    {
        rank: 46,
        name: "Michael",
        year: 2002,
        score: 360,
        percentage: 84,
    },
    {
        rank: 47,
        name: "Mia",
        year: 1994,
        score: 470,
        percentage: 92,
    },
    {
        rank: 48,
        name: "David",
        year: 1996,
        score: 330,
        percentage: 86,
    },
    {
        rank: 49,
        name: "Liam",
        year: 1999,
        score: 610,
        percentage: 94,
    },
    {
        rank: 50,
        name: "Sophia",
        year: 2000,
        score: 400,
        percentage: 89,
    },
    {
        rank: 51,
        name: "Lucas",
        year: 1995,
        score: 260,
        percentage: 87,
    },
    {
        rank: 52,
        name: "Daniel",
        year: 1992,
        score: 480,
        percentage: 82,
    },
    {
        rank: 53,
        name: "Olivia",
        year: 1998,
        score: 660,
        percentage: 98,
    },
    {
        rank: 54,
        name: "Emily",
        year: 1997,
        score: 540,
        percentage: 91,
    },
    {
        rank: 55,
        name: "Jacob",
        year: 2004,
        score: 370,
        percentage: 85,
    },
    {
        rank: 56,
        name: "Elijah",
        year: 1996,
        score: 430,
        percentage: 93,
    },
    {
        rank: 57,
        name: "Isabella",
        year: 1992,
        score: 400,
        percentage: 82,
    },
    {
        rank: 58,
        name: "Ava",
        year: 1995,
        score: 520,
        percentage: 88,
    },
];
